export class APP_CONSTANTS {
    // weather to symbol id and display name mapping
    public static SYMBOL_DATA: any = {
        clearsky_day: { symbol_id: "01d", name: "Clear Sky"},
        clearsky_night: { symbol_id: "01n", name: "Clear Sky"},
        clearsky_polartwilight: { symbol_id: "01m", name: "Clear Sky"},
        fair_day: { symbol_id: "02d", name: "Fair"},
        fair_night: { symbol_id: "02n", name: "Fair"},
        fair_polartwilight: { symbol_id: "02m", name: "Fair"},
        partlycloudy_day: { symbol_id: "03d", name: "Partly Cloudy"},
        partlycloudy_night: { symbol_id: "03n", name: "Partly Cloudy"},
        partlycloudy_polartwilight: { symbol_id: "03m", name: "Partly Cloudy"},
        cloudy: { symbol_id: "04", name: "Cloudy"},
        rainshowers_day: { symbol_id: "05d", name: "Rain Showers"},
        rainshowers_night: { symbol_id: "05n", name: "Rain Showers"},
        rainshowers_polartwilight: { symbol_id: "05m", name: "Rain Showers"},
        rainshowersandthunder_day: { symbol_id: "06d", name: "Rain showers and thunder"},
        rainshowersandthunder_night: { symbol_id: "06n", name: "Rain showers and thunder"},
        rainshowersandthunder_polartwilight: { symbol_id: "06m", name: "Rain showers and thunder"},
        sleetshowers_day: { symbol_id: "07d", name: "Sleet showers"},
        sleetshowers_night: { symbol_id: "07n", name: "Sleet showers"},
        sleetshowers_polartwilight: { symbol_id: "07m", name: "Sleet showers"},
        snowshowers_day: { symbol_id: "08d", name: "Snow showers"},
        snowshowers_night: { symbol_id: "08n", name: "Snow showers"},
        snowshowers_polartwilight: { symbol_id: "08m", name: "Snow showers"},
        rain: { symbol_id: "09", name: "Rain"},
        heavyrain: { symbol_id: "10", name: "Heavy rain"},
        heavyrainandthunder: { symbol_id: "11", name: "Heavy rain and thunder"},
        sleet: { symbol_id: "12", name: "Sleet"},
        snow: { symbol_id: "13", name: "Snow"},
        snowandthunder: { symbol_id: "14", name: "Snow and thunder"},
        fog: { symbol_id: "15", name: "Fog"},
        sleetshowersandthunder_day: { symbol_id: "20d", name: "Sleet showers and thunder"},
        sleetshowersandthunder_night: { symbol_id: "20n", name: "Sleet showers and thunder"},
        sleetshowersandthunder_polartwilight: { symbol_id: "20m", name: "Sleet showers and thunder"},
        snowshowersandthunder_day: { symbol_id: "21d", name: "Snow showers and thunder"},
        snowshowersandthunder_night: { symbol_id: "21n", name: "Snow showers and thunder"},
        snowshowersandthunder_polartwilight: { symbol_id: "21m", name: "Snow showers and thunder"},
        rainandthunder: { symbol_id: "22", name: "Rain and thunder"},
        sleetandthunder: { symbol_id: "23", name: "Sleet and thunder"},
        lightrainshowersandthunder_day: { symbol_id: "24d", name: "Light rain showers and thunder"},
        lightrainshowersandthunder_night: { symbol_id: "24n", name: "Light rain showers and thunder"},
        lightrainshowersandthunder_polartwilight: { symbol_id: "24m", name: "Light rain showers and thunder"},
        heavyrainshowersandthunder_day: { symbol_id: "25d", name: "Heavy rain showers and thunder"},
        heavyrainshowersandthunder_night: { symbol_id: "25n", name: "Heavy rain showers and thunder"},
        heavyrainshowersandthunder_polartwilight: { symbol_id: "25m", name: "Heavy rain showers and thunder"},
        lightssleetshowersandthunder_day: { symbol_id: "26d", name: "Light sleet showers and thunder"},
        lightssleetshowersandthunder_night: { symbol_id: "26n", name: "Light sleet showers and thunder"},
        lightssleetshowersandthunder_polartwilight: { symbol_id: "26m", name: "Light sleet showers and thunder"},
        heavysleetshowersandthunder_day: { symbol_id: "27d", name: "Heavy sleet showers and thunder"},
        heavysleetshowersandthunder_night: { symbol_id: "27n", name: "Heavy sleet showers and thunder"},
        heavysleetshowersandthunder_polartwilight: { symbol_id: "27m", name: "Heavy sleet showers and thunder"},
        lightssnowshowersandthunder_day: { symbol_id: "28d", name: "Light snow showers and thunder"},
        lightssnowshowersandthunder_night: { symbol_id: "28n", name: "Light snow showers and thunder"},
        lightssnowshowersandthunder_polartwilight: { symbol_id: "28m", name: "Light snow showers and thunder"},
        heavysnowshowersandthunder_day: { symbol_id: "29d", name: "Heavy snow showers and thunder"},
        heavysnowshowersandthunder_night: { symbol_id: "29n", name: "Heavy snow showers and thunder"},
        heavysnowshowersandthunder_polartwilight: { symbol_id: "29m", name: "Heavy snow showers and thunder"},
        lightrainandthunder: { symbol_id: "30", name: "Light rain and thunder"},
        lightsleetandthunder: { symbol_id: "31", name: "Light sleet and thunder"},
        heavysleetandthunder: { symbol_id: "32", name: "Heavy sleet and thunder"},
        lightsnowandthunder: { symbol_id: "33", name: "Light snow and thunder"},
        heavysnowandthunder: { symbol_id: "34", name: "Heavy snow and thunder"},
        lightrainshowers_day: { symbol_id: "40d", name: "Light rain showers"},
        lightrainshowers_night: { symbol_id: "40n", name: "Light rain showers"},
        lightrainshowers_polartwilight: { symbol_id: "40m", name: "Light rain showers"},
        heavyrainshowers_day: { symbol_id: "41d", name: "Heavy rain showers"},
        heavyrainshowers_night: { symbol_id: "41n", name: "Heavy rain showers"},
        heavyrainshowers_polartwilight: { symbol_id: "41m", name: "Heavy rain showers"},
        lightsleetshowers_day: { symbol_id: "42d", name: "Light sleet showers"},
        lightsleetshowers_night: { symbol_id: "42n", name: "Light sleet showers"},
        lightsleetshowers_polartwilight: { symbol_id: "42m", name: "Light sleet showers"},
        heavysleetshowers_day: { symbol_id: "43d", name: "Heavy sleet showers"},
        heavysleetshowers_night: { symbol_id: "43n", name: "Heavy sleet showers"},
        heavysleetshowers_polartwilight: { symbol_id: "43m", name: "Heavy sleet showers"},
        lightsnowshowers_day: { symbol_id: "44d", name: "Light snow showers"},
        lightsnowshowers_night: { symbol_id: "44n", name: "Light snow showers"},
        lightsnowshowers_polartwilight: { symbol_id: "44m", name: "Light snow showers"},
        heavysnowshowers_day: { symbol_id: "45d", name: "Heavy snow showers"},
        heavysnowshowers_night: { symbol_id: "45n", name: "Heavy snow showers"},
        heavysnowshowers_polartwilight: { symbol_id: "45m", name: "Heavy snow showers"},
        lightrain: { symbol_id: "46", name: "Light rain"},
        lightsleet: { symbol_id: "47", name: "Light sleet"},
        heavysleet: { symbol_id: "48", name: "Heavy sleet"},
        lightsnow: { symbol_id: "49", name: "Light snow"},
        heavysnow: { symbol_id: "50", name: "Heavy snow"}
    }
}